name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    shell: bash
    run: |-
      echo '
        target: ${{ env.dist }}
        setup:
          run: pnpm build
          cwd: ./ember-velcro
        expect: |
          index.js
          index.js.map
          index.d.ts
          components/velcro/index.js
          modifiers/velcro.js
          
      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v3
    with:
      name: dist
      path: ${{ env.dist }}
  - name: 'Install dependencies'
    shell: 'bash'
    run: pnpm install
