name: Setup node and pnpm
description: Setup node and install dependencies using pnpm
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 7
    - uses: actions/setup-node@v3
      with:
        cache: 'pnpm'
    - name: 'Install dependencies'
      shell: 'bash'
      run: pnpm install
    # TODO: use https://github.com/NullVoxPopuli/pnpm-sync-dependencies-meta-injected
    - name: build
      shell: 'bash'
      run: pnpm build
    - name: force re-linking
      shell: 'bash'
      run: pnpm i -f
